name: Build & Release

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Release tag (e.g. v1.0.0)'
        required: true

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Build all targets
        run: |
          mkdir -p out

          # Build server binaries
          GOOS=linux   GOARCH=amd64 go build -tags server -o out/xmlui-mcp                 # linux
          GOOS=windows GOARCH=amd64 go build -tags server -o out/xmlui-mcp.exe             # windows
          GOOS=darwin  GOARCH=amd64 go build -tags server -o out/xmlui-mcp-mac-amd         # mac-amd (temp)
          GOOS=darwin  GOARCH=arm64 go build -tags server -o out/xmlui-mcp-mac-arm         # mac-arm (temp)

          # Build client binaries
          GOOS=linux   GOARCH=amd64 go build -tags client -o out/xmlui-mcp-client          # linux
          GOOS=windows GOARCH=amd64 go build -tags client -o out/xmlui-mcp-client.exe      # windows
          GOOS=darwin  GOARCH=amd64 go build -tags client -o out/xmlui-mcp-client-mac-amd  # mac-amd (temp)
          GOOS=darwin  GOARCH=arm64 go build -tags client -o out/xmlui-mcp-client-mac-arm  # mac-arm (temp)

          # Copy startup scripts into the build output
          cp run-mcp-client.sh out/
          cp run-mcp-client.bat out/

          cd out

          # Package mac-amd
          mv xmlui-mcp-mac-amd xmlui-mcp
          mv xmlui-mcp-client-mac-amd xmlui-mcp-client
          zip xmlui-mcp-mac-amd.zip xmlui-mcp xmlui-mcp-client run-mcp-client.sh

          # Package mac-arm
          mv xmlui-mcp-mac-arm xmlui-mcp
          mv xmlui-mcp-client-mac-arm xmlui-mcp-client
          zip xmlui-mcp-mac-arm.zip xmlui-mcp xmlui-mcp-client run-mcp-client.sh

          # Package linux
          zip xmlui-mcp-linux-amd64.zip xmlui-mcp xmlui-mcp-client run-mcp-client.sh

          # Package windows
          mv xmlui-mcp.exe xmlui-mcp
          mv xmlui-mcp-client.exe xmlui-mcp-client
          zip xmlui-mcp-windows.zip xmlui-mcp xmlui-mcp-client run-mcp-client.bat

      - name: Upload to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.event.inputs.tag }}
          files: out/*.zip
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
