# .github/workflows/release.yml
name: Release Binaries

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Release tag (e.g. v1.2.3)'
        required: true

jobs:
  build:
    name: Build and Release
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, windows, darwin, darwin]
        goarch: [amd64, amd64, amd64, arm64]
        exclude:
          - goos: linux
            goarch: arm64
          - goos: windows
            goarch: arm64
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Set env vars
        run: |
          echo "EXT=$([[ '${{ matrix.goos }}' == 'windows' ]] && echo '.exe' || echo '')" >> $GITHUB_ENV

      - name: Build
        run: |
          mkdir -p build
          GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} go build -v -o build/xmlui-mcp-${{ matrix.goos }}-${{ matrix.goarch }}$EXT

      - name: Archive
        run: |
          cd build
          zip xmlui-mcp-${{ matrix.goos }}-${{ matrix.goarch }}.zip xmlui-mcp-${{ matrix.goos }}-${{ matrix.goarch }}$EXT

      - name: Upload Release Asset
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.event.inputs.tag }}
          files: build/*.zip
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
