# .github/workflows/release.yml
name: Build & Release

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Release tag (e.g. v1.0.0)'
        required: true

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Build all targets
        run: |
          mkdir out

          GOOS=linux   GOARCH=amd64 go build -o out/xmlui-mcp-linux-amd64
          GOOS=windows GOARCH=amd64 go build -o out/xmlui-mcp-windows-amd64.exe
          GOOS=darwin  GOARCH=amd64 go build -o out/xmlui-mcp-macos-amd64
          GOOS=darwin  GOARCH=arm64 go build -o out/xmlui-mcp-macos-arm64

          cd out
          zip xmlui-mcp-linux-amd64.zip        xmlui-mcp-linux-amd64
          zip xmlui-mcp-windows-amd64.zip      xmlui-mcp-windows-amd64.exe
          zip xmlui-mcp-macos-amd64.zip        xmlui-mcp-macos-amd64
          zip xmlui-mcp-macos-arm64.zip        xmlui-mcp-macos-arm64

      - name: Upload to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.event.inputs.tag }}
          files: |
            out/*.zip
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
